#pragma once

// GENERATED by tools/spectral_weights.py -- do not edit. Run the script.
//
// The plate exposure of each of Smits' seven basis reflectances under each
// light, white normalised to exactly 1. The shader sums these the way Smits
// sums the spectra. Sources and method are in the script.

namespace wetplate::spectral
{

constexpr int kLightCount = 3;

/// Order: white, cyan, magenta, yellow, red, green, blue.
struct Weights
{
	const char* light;
	float kelvin;
	float w[ 7 ];
};

constexpr Weights kWeights[ kLightCount ] = {
	{ "Daylight", 6504.0f, { 1.0f, 0.963185049f, 0.98380056f, 0.0198556533f, 0.073701063f, 0.0162116239f, 0.9802007f } },
	{ "Tungsten", 2856.0f, { 1.0f, 0.964396771f, 0.956788309f, 0.0483211701f, 0.0609575768f, 0.043508591f, 0.951691792f } },
	{ "Flash", 5500.0f, { 1.0f, 0.963184111f, 0.98125561f, 0.022650139f, 0.0720941419f, 0.0187768184f, 0.977402235f } },
};

/// The sensitivity table as committed, for the record: relative sensitivity
/// from 380 nm at 10 nm steps.
constexpr int kSensitivityStartNm = 380;
constexpr int kSensitivityCount   = 15;
constexpr float kSensitivity[ kSensitivityCount ] = { 1.00f, 1.02f, 1.03f, 1.05f, 1.00f, 0.80f, 0.35f, 0.22f, 0.14f, 0.10f, 0.08f, 0.05f, 0.03f, 0.01f, 0.00f };

} // namespace wetplate::spectral
