/*
 * Stoatworks Labs - About window data for Wetplate.
 *
 * PROVISIONAL hand copy, adapted from a sibling (rebate) on 2026-09-24. The
 * fleet's copies are GENERATED by stoatworks-backend/scripts/sync-about.py
 * from the website's projects.json; this plugin is not on the website yet,
 * so there is nothing to generate from. The next sync overwrites this file.
 *
 * `guide` is empty on purpose: no user guide exists yet, and an empty link
 * leaves its button out of the About block rather than opening a 404.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Wetplate";
    inline constexpr auto slug = "wetplate";
    inline constexpr auto hook = "A collodion wet plate, blue-sensitive and seconds long, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/wetplate/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/wetplate";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
